name: snake
description: A flexible snake implementation in Dart.
version: 0.1.0
homepage: https://github.com/hacker1024/snake.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lint: ^1.5.3
